on: [ push ]
name: check
# https://github.com/actions/setup-haskell
jobs:
  linter:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pusher.name, '[bot]') }}
    steps:
      - uses: actions/checkout@v3

      - name: 'Setup HLint'
        uses: haskell-actions/hlint-setup@v2

      - name: 'Run HLint'
        uses: haskell-actions/hlint-run@v2
        with:
          path: src/
          fail-on: warning

  tests:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pusher.name, '[bot]') }}
    timeout-minutes: 5
    continue-on-error: true
    env:
      HASKELL_TEST_REPORT: report.txt
    steps:
      - uses: actions/checkout@v3

      - name: 'Setup GHC with Stack'
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.7'
          enable-stack: true
          stack-version: 'latest'

      - name: 'Build all'
        run: stack build --test --no-run-tests --system-ghc

      - name: 'Run 1.1 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '1.1'

      - name: 'Run 1.2 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '1.2'

      - name: 'Run 1.3 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '1.3'

      - name: 'Run 1.4 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '1.4'

      - name: 'Run 1.5 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '1.5'

      - name: 'Run 1.6 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '1.6'

      - name: 'Run 1.7 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '1.7'

      - name: 'Run 1.8 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '1.8'

      - name: 'Run 1.9 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '1.9'

      - name: 'Run 1.10 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '1.10'

      - name: 'Run 2.1 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '2.1'

      - name: 'Run 2.2 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '2.2'

      - name: 'Run 2.3 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '2.3'

      - name: 'Run 2.4 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '2.4'

      - name: 'Run 2.5 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '2.5'

      - name: 'Run 2.6 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '2.6'

      - name: 'Run 2.7 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '2.7'

      - name: 'Run 2.8 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '2.8'

      - name: 'Run 2.9 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '2.9'

      - name: 'Run 2.10 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '2.10'

      - name: 'Run 3.1 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '3.1'

      - name: 'Run 3.2 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '3.2'

      - name: 'Run 3.3 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '3.3'

      - name: 'Run 3.4 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '3.4'

      - name: 'Run 3.5 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '3.5'

      - name: 'Run 3.6 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '3.6'

      - name: 'Run 3.7 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '3.7'

      - name: 'Run 3.8 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '3.8'

      - name: 'Run 3.9 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '3.9'

      - name: 'Run 3.10 test'
        if: ${{ always() }}
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/run.sh '3.10'

      - name: 'Upload results'
        uses: actions/upload-artifact@v4
        with:
          name: Report
          path: report.txt
